//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 

package com.realdolmen.fleet.webservices.endpoints;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for carModelXml complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="carModelXml">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="horsePower" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cilinder" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="motorType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="gears" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="emission" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="line" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "carModelXml", propOrder = {
    "id",
    "model",
    "mark",
    "horsePower",
    "cilinder",
    "motorType",
    "gears",
    "emission",
    "line",
    "category"
})
public class CarModelXml {

    protected int id;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(required = true)
    protected String mark;
    protected int horsePower;
    protected int cilinder;
    protected int motorType;
    protected int gears;
    protected int emission;
    @XmlElement(required = true)
    protected String line;
    protected int category;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the mark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMark() {
        return mark;
    }

    /**
     * Sets the value of the mark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMark(String value) {
        this.mark = value;
    }

    /**
     * Gets the value of the horsePower property.
     * 
     */
    public int getHorsePower() {
        return horsePower;
    }

    /**
     * Sets the value of the horsePower property.
     * 
     */
    public void setHorsePower(int value) {
        this.horsePower = value;
    }

    /**
     * Gets the value of the cilinder property.
     * 
     */
    public int getCilinder() {
        return cilinder;
    }

    /**
     * Sets the value of the cilinder property.
     * 
     */
    public void setCilinder(int value) {
        this.cilinder = value;
    }

    /**
     * Gets the value of the motorType property.
     * 
     */
    public int getMotorType() {
        return motorType;
    }

    /**
     * Sets the value of the motorType property.
     * 
     */
    public void setMotorType(int value) {
        this.motorType = value;
    }

    /**
     * Gets the value of the gears property.
     * 
     */
    public int getGears() {
        return gears;
    }

    /**
     * Sets the value of the gears property.
     * 
     */
    public void setGears(int value) {
        this.gears = value;
    }

    /**
     * Gets the value of the emission property.
     * 
     */
    public int getEmission() {
        return emission;
    }

    /**
     * Sets the value of the emission property.
     * 
     */
    public void setEmission(int value) {
        this.emission = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine(String value) {
        this.line = value;
    }

    /**
     * Gets the value of the category property.
     * 
     */
    public int getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     */
    public void setCategory(int value) {
        this.category = value;
    }

}
