//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
<<<<<<< HEAD
// Generated on: 2015.11.02 at 10:44:19 AM CET 
=======
// Generated on: 2015.11.02 at 10:37:10 AM CET 
>>>>>>> refs/remotes/origin/master
=======
// Generated on: 2015.10.30 at 05:00:56 PM CET 
>>>>>>> refs/remotes/origin/master
//


package com.realdolmen.fleet.webservices.endpoints;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.realdolmen.fleet.webservices.endpoints package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.realdolmen.fleet.webservices.endpoints
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCarModelRequest }
     * 
     */
    public GetCarModelRequest createGetCarModelRequest() {
        return new GetCarModelRequest();
    }

    /**
     * Create an instance of {@link GetCarModelResponse }
     * 
     */
    public GetCarModelResponse createGetCarModelResponse() {
        return new GetCarModelResponse();
    }

    /**
     * Create an instance of {@link CarModelXml }
     * 
     */
    public CarModelXml createCarModelXml() {
        return new CarModelXml();
    }

}
