//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2015.10.30 at 05:00:56 PM CET 
=======
<<<<<<< HEAD
// Generated on: 2015.11.02 at 10:44:19 AM CET 
=======
// Generated on: 2015.11.02 at 10:37:10 AM CET 
>>>>>>> refs/remotes/origin/master
>>>>>>> refs/remotes/origin/Steven
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://realdolmen.com/fleet/webservices/endpoints", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.realdolmen.fleet.webservices.endpoints;
